version: '3'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
  api:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    ports:
      - '3000:3000'
    command: ["npm","run","dev"]

